name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1: Vérifiez le code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape 2: Configurez Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Étape 3: Construisez et testez avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

      # Étape 4: Analyse de qualité avec SonarCloud
      - name: SonarCloud Analysis
        working-directory: ./simple-api
        run: mvn -B verify sonar:sonar \
              -Dsonar.projectKey=RemyDmK_tp_big_data_1 \
              -Dsonar.organization=remydmk \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
